require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'sample' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'sampleTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper! ({ 'Flipper' => '0.95.0' })
  post_install do |installer|
    flipper_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_BITCODE'] = 'NO'
      end
    end
  end
end

target 'sample-tvOS' do
  # Pods for sample-tvOS

  target 'sample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
